[{"ContainerToolsException.Message":"Docker command failed with exit code 1. #1 [internal] load build definition from Dockerfile #1 sha256:e07ba56e0fca63b17160e79372ad1c99d18a92f66440741cba9a286755775036 #1 transferring dockerfile: 32B done #1 DONE 0.0s  #2 [internal] load .dockerignore #2 sha256:461c941121d99ce639620cf97db765594adfa1c0bcc561dcff8c187fbff33d77 #2 transferring context: 35B done #2 DONE 0.0s  #3 [internal] load metadata for mcr.microsoft.com/dotnet/sdk:3.1 #3 sha256:ce64eac29b07ebbf4d973b99e492aaf8ba85556a3d349a716d703b36362d10a7 #3 DONE 0.0s  #5 [internal] load build context #5 sha256:abf70901be5a9e8498f9e571fd3319de726a699627646a1bbc4b72b687d3e0ee #5 transferring context: 671B done #5 DONE 0.0s  #4 [1/6] FROM mcr.microsoft.com/dotnet/sdk:3.1 #4 sha256:ac91ae69d06f041dd900f290206b53db04266b5fa97c5116cc4391f50f6d93bc #4 CACHED  #6 [2/6] COPY . /app #6 sha256:d67e0d40011caa12e7796b0a2536fc427c60619b07f31620305cebd585f54843 #6 DONE 0.0s  #7 [3/6] WORKDIR /app #7 sha256:c080d95bcac89cd3d2aa465733c5b742cf6155d95d44ba1200bd801d4cbbc0c5 #7 DONE 0.1s  #8 [4/6] RUN [\"dotnet\", \"restore\"] #8 sha256:a5399fd74644199862ce3a6e2fe9001e05c858a5583d9707c8cff330700b5279 #8 0.729 /usr/share/dotnet/sdk/3.1.418/NuGet.targets(282,5): error MSB3202: The project file \"/app/docker-compose.dcproj\" was not found. [/app/LongestIncreasingSequence.sln] #8 ERROR: executor failed running [dotnet restore]: exit code: 1 ------  > [4/6] RUN [\"dotnet\", \"restore\"]: ------ executor failed running [dotnet restore]: exit code: 1","ContainerToolsException.ErrorCode":"CTC1014","ContainerToolsException.StackTrace":"   at Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<BuildImageAsync>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<RebuildImageAsync>d__12.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchForDockerfileAsync>d__7.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildAndLaunch.<ExecuteCoreAsync>d__180.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__26.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.FaultingUserFile.FilePath":"Dockerfile","ContainerToolsException.FaultingUserFile.LineStart":"","ContainerToolsException.FaultingUserFile.ColumnStart":"","ContainerToolsException.FaultingUserFile.LineEnd":"","ContainerToolsException.FaultingUserFile.ColumnEnd":"","ContainerToolsException.CommandLine.Program":"docker","ContainerToolsException.CommandLine.TelemetrySafeArguments":"build","ContainerToolsException.CommandLine.ExitCode":"1","ContainerToolsException.CommandLine.ErrorOutput":"#1 [internal] load build definition from Dockerfile\r\n#1 sha256:e07ba56e0fca63b17160e79372ad1c99d18a92f66440741cba9a286755775036\r\n#1 transferring dockerfile: 32B done\r\n#1 DONE 0.0s\r\n\r\n#2 [internal] load .dockerignore\r\n#2 sha256:461c941121d99ce639620cf97db765594adfa1c0bcc561dcff8c187fbff33d77\r\n#2 transferring context: 35B done\r\n#2 DONE 0.0s\r\n\r\n#3 [internal] load metadata for mcr.microsoft.com/dotnet/sdk:3.1\r\n#3 sha256:ce64eac29b07ebbf4d973b99e492aaf8ba85556a3d349a716d703b36362d10a7\r\n#3 DONE 0.0s\r\n\r\n#5 [internal] load build context\r\n#5 sha256:abf70901be5a9e8498f9e571fd3319de726a699627646a1bbc4b72b687d3e0ee\r\n#5 transferring context: 671B done\r\n#5 DONE 0.0s\r\n\r\n#4 [1/6] FROM mcr.microsoft.com/dotnet/sdk:3.1\r\n#4 sha256:ac91ae69d06f041dd900f290206b53db04266b5fa97c5116cc4391f50f6d93bc\r\n#4 CACHED\r\n\r\n#6 [2/6] COPY . /app\r\n#6 sha256:d67e0d40011caa12e7796b0a2536fc427c60619b07f31620305cebd585f54843\r\n#6 DONE 0.0s\r\n\r\n#7 [3/6] WORKDIR /app\r\n#7 sha256:c080d95bcac89cd3d2aa465733c5b742cf6155d95d44ba1200bd801d4cbbc0c5\r\n#7 DONE 0.1s\r\n\r\n#8 [4/6] RUN [\"dotnet\", \"restore\"]\r\n#8 sha256:a5399fd74644199862ce3a6e2fe9001e05c858a5583d9707c8cff330700b5279\r\n#8 0.729 /usr/share/dotnet/sdk/3.1.418/NuGet.targets(282,5): error MSB3202: The project file \"/app/docker-compose.dcproj\" was not found. [/app/LongestIncreasingSequence.sln]\r\n#8 ERROR: executor failed running [dotnet restore]: exit code: 1\r\n------\r\n > [4/6] RUN [\"dotnet\", \"restore\"]:\r\n------\r\nexecutor failed running [dotnet restore]: exit code: 1"}]